### ISSUE TITLE
Turtlebot's LCD doesn't come out

### ISSUE THREAD

**Issue by rhyeonwoo** [turtlebot/turtlebot4#154] opened 2023-04-28 06:00 UTC
Turtlebot's LCD doesn't come out and joysticks don't connect.
Raspberry Pi and Create PC Wi-Fi are connected.
If I look at the topic, I can't see it all.  I compared it with other Turtle Bot products.
I think the Raspberry Pi has a light on, so the power is on.

I think mcu is the problem, is there any other problem?
![turtlebot lcd](https://user-images.githubusercontent.com/100173088/235065859-4f5fb45e-d9c3-49d6-8a24-b019254afad8.png)

**Comment by roni-kreinin** [comment] 2023-04-28 14:45
Closing as duplicate of #156

**Closed as completed by roni-kreinin** 2023-04-28 14:45 UTC
Labels: enhancement
