### ISSUE TITLE
Turtlebot 4 discovery Server Problem

### ISSUE THREAD

**Issue by Markyyy55** [turtlebot/turtlebot4#179] opened 2023-05-25 23:07 UTC
I have a problem with the turtlebot4 the navigation does not work. So I did exactly what the manual told me to do. Normally you start to make the map and then can drive around to scan it. For visualization there is the command so that I can view where the turtlebot4 is. The problem is the view does not show anything. Just a grey box and a warning that no map received. 

So we wanted to make the discovery server so that there is a connection with create 3 and raspberry Pi. Also here we did everything what the manual told. But then after the option where we need to enter the ip and port of the discovery server, we just get this: rtnelink answers: no such process 

Please help

**Comment by roni-kreinin** [comment] 2023-05-26 14:20
Closing as duplicate of #180

**Closed as completed by roni-kreinin** 2023-05-26 14:20 UTC
Labels: enhancement
