### ISSUE TITLE
Front bumber pops out in RVIZ 

### ISSUE THREAD

**Issue by ipa-rar** [turtlebot/turtlebot4#162] opened 2023-05-08 13:27 UTC
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS Distro: Humble
 -  installed:
 - Package version: humble

 **Expected behaviour**
robot model without any anomalies

 **Actual behaviour**
 The front bumber of the robot appears to be in  a popped out state.

**To Reproduce**
Provide the steps to reproduce:
`ros2 launch turtlebot4_viz view_robot.launch.py`

**Other notes**
![Screenshot from 2023-05-08 15-18-38](https://user-images.githubusercontent.com/49311464/236836348-ec62b345-e27e-48fb-86f8-cda5b9919bd8.png)

**Comment by roni-kreinin** [comment] 2023-05-15 17:55
Duplicate of https://github.com/iRobotEducation/create3_sim/issues/170. The issue is fixed in the source package and the debian should be released soon.

**Closed as completed by roni-kreinin** 2023-05-15 17:55 UTC
Labels: bug
